name: Component Tests

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main
jobs:
  run-component-tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-noble
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: true
      - name: Install dependencies
        run: pnpm install
      - name: Run Playwright tests
        run: pnpm run test:component
        env:
          BASE_URL: ${{ github.event.deployment_status.target_url }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-component
          path: playwright-report/
          retention-days: 30