name: Types

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

jobs:
  types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: true
      - name: Install dependencies
        run: pnpm install
      - name: Run type checker
        run: pnpm run types
